translations/ui-plugin-create-inventory-records/ar.json
translations/ui-plugin-create-inventory-records/ca.json
translations/ui-plugin-create-inventory-records/da.json
translations/ui-plugin-create-inventory-records/de.json
translations/ui-plugin-create-inventory-records/en_GB.json
translations/ui-plugin-create-inventory-records/en_SE.json
translations/ui-plugin-create-inventory-records/en_US.json
translations/ui-plugin-create-inventory-records/es.json
translations/ui-plugin-create-inventory-records/es_419.json
translations/ui-plugin-create-inventory-records/es_ES.json
translations/ui-plugin-create-inventory-records/fr.json
translations/ui-plugin-create-inventory-records/fr_FR.json
translations/ui-plugin-create-inventory-records/he.json
translations/ui-plugin-create-inventory-records/hu.json
translations/ui-plugin-create-inventory-records/it_IT.json
translations/ui-plugin-create-inventory-records/ja.json
translations/ui-plugin-create-inventory-records/pt_BR.json
translations/ui-plugin-create-inventory-records/pt_PT.json
translations/ui-plugin-create-inventory-records/ru.json
translations/ui-plugin-create-inventory-records/ur.json
translations/ui-plugin-create-inventory-records/zh_CN.json
translations/ui-plugin-create-inventory-records/zh_TW.json

Update translation strings as of 20200728T221039

---

translations/ui-plugin-create-inventory-records/ar.json
translations/ui-plugin-create-inventory-records/pt_BR.json

Update translation strings as of 20200804T124827

---

translations/ui-plugin-create-inventory-records/ar.json
translations/ui-plugin-create-inventory-records/ca.json
translations/ui-plugin-create-inventory-records/da.json
translations/ui-plugin-create-inventory-records/de.json
translations/ui-plugin-create-inventory-records/en_GB.json
translations/ui-plugin-create-inventory-records/en_SE.json
translations/ui-plugin-create-inventory-records/en_US.json
translations/ui-plugin-create-inventory-records/es.json
translations/ui-plugin-create-inventory-records/es_419.json
translations/ui-plugin-create-inventory-records/es_ES.json
translations/ui-plugin-create-inventory-records/fr.json
translations/ui-plugin-create-inventory-records/fr_FR.json
translations/ui-plugin-create-inventory-records/he.json
translations/ui-plugin-create-inventory-records/hu.json
translations/ui-plugin-create-inventory-records/it_IT.json
translations/ui-plugin-create-inventory-records/ja.json
translations/ui-plugin-create-inventory-records/pt_BR.json
translations/ui-plugin-create-inventory-records/pt_PT.json
translations/ui-plugin-create-inventory-records/ru.json
translations/ui-plugin-create-inventory-records/ur.json
translations/ui-plugin-create-inventory-records/zh_CN.json
translations/ui-plugin-create-inventory-records/zh_TW.json

Update translation strings as of 20200806T130626

---

CHANGELOG.md
src/CreateRecordsForm.js
src/CreateRecordsWrapper.js
src/components/HoldingAccordion/HoldingAccordion.js
src/components/HoldingAccordion/index.js
src/components/index.js
src/providers/DataProvider.js
src/util.js
test/bigtest/interactors/createRecordsPlugin.js
test/bigtest/network/config.js
test/bigtest/network/factories/item.js
test/bigtest/tests/create-records-plugin-test.js
translations/ui-plugin-create-inventory-records/en.json

Create holdings record via fast add form.
https://issues.folio.org/browse/UIPCIR-2

UIPCIR-2: Create holdings record via fast add form

---

translations/ui-plugin-create-inventory-records/ar.json
translations/ui-plugin-create-inventory-records/ca.json
translations/ui-plugin-create-inventory-records/da.json
translations/ui-plugin-create-inventory-records/de.json
translations/ui-plugin-create-inventory-records/en_GB.json
translations/ui-plugin-create-inventory-records/en_SE.json
translations/ui-plugin-create-inventory-records/en_US.json
translations/ui-plugin-create-inventory-records/es.json
translations/ui-plugin-create-inventory-records/es_419.json
translations/ui-plugin-create-inventory-records/es_ES.json
translations/ui-plugin-create-inventory-records/fr.json
translations/ui-plugin-create-inventory-records/fr_FR.json
translations/ui-plugin-create-inventory-records/he.json
translations/ui-plugin-create-inventory-records/hu.json
translations/ui-plugin-create-inventory-records/it_IT.json
translations/ui-plugin-create-inventory-records/ja.json
translations/ui-plugin-create-inventory-records/pt_BR.json
translations/ui-plugin-create-inventory-records/pt_PT.json
translations/ui-plugin-create-inventory-records/ru.json
translations/ui-plugin-create-inventory-records/ur.json
translations/ui-plugin-create-inventory-records/zh_CN.json
translations/ui-plugin-create-inventory-records/zh_TW.json

Update translation strings as of 20200811T193833

---

src/components/InstanceAccordion/InstanceAccordion.js
src/providers/DataProvider.js
src/util.js
test/bigtest/interactors/createRecordsPlugin.js
test/bigtest/network/config.js
test/bigtest/network/factories/instance-status.js
test/bigtest/network/models/instance-status.js
test/bigtest/network/scenarios/default.js
test/bigtest/network/serializers/instance-status.js
test/bigtest/tests/create-records-plugin-test.js
translations/ui-plugin-create-inventory-records/en.json

This PR includes couple additional fixes related to instance status and publication date found by Cate under: 
https://issues.folio.org/browse/UIPCIR-1

UIPCIR-1: Fix instance status and publication date

---

CHANGELOG.md
src/CreateRecordsWrapper.js
src/providers/DataProvider.js

https://issues.folio.org/browse/UIPCIR-7
Set the initial values according to the defaults specified in Settings ([UIIN-1211](https://issues.folio.org/browse/UIIN-1211)) when creating a Fast add record.

UIPCIR-7: Add defaults from Settings when creating a fast add record

---

translations/ui-plugin-create-inventory-records/ja.json

Update translation strings as of 20200914T140557

---

package.json
src/CreateRecordsForm.js
src/providers/DataProvider.js
test/bigtest/interactors/createRecordsPlugin.js
test/bigtest/network/config.js
test/bigtest/network/scenarios/default.js
test/bigtest/tests/create-records-plugin-test.js

I added couple more tests and some cleanup work but the cause of the low coverage was related to the fact that only 2 tests were running and BigTest would just hang after that. The problem went away after I upgraded react-intl  🤷

Improve test coverage

---

translations/ui-plugin-create-inventory-records/pt_BR.json

Update translation strings as of 20200922T125348

---

translations/ui-plugin-create-inventory-records/ru.json

Update translation strings as of 20200928T202231

---

translations/ui-plugin-create-inventory-records/it_IT.json

Update translation strings as of 20201008T220807

---

translations/ui-plugin-create-inventory-records/de.json

Update translation strings as of 20201102T140138

---

translations/ui-plugin-create-inventory-records/ja.json

Update translation strings as of 20201105T151643

---

translations/ui-plugin-create-inventory-records/it_IT.json

Update translation strings as of 20201111T142927

---

translations/ui-plugin-create-inventory-records/it_IT.json
translations/ui-plugin-create-inventory-records/ja.json

Update translation strings as of 20201124T212804

---

CHANGELOG.md
package.json

https://issues.folio.org/projects/UIPCIR/issues/UIPCIR-16

UIPCIR-16: Upgrade to stripes v6

---

CHANGELOG.md
src/components/CirculationNoteFields/CirculationNoteFields.js
src/components/ContributorFields/ContributorFields.js
src/components/ElectronicAccessFields/ElectronicAccessFields.js
src/components/HoldingAccordion/HoldingAccordion.js
src/components/InstanceAccordion/InstanceAccordion.js
src/components/ItemAccordion/ItemAccordion.js
src/util.js
test/bigtest/interactors/createRecordsPlugin.js
test/bigtest/network/config.js
test/bigtest/tests/create-records-plugin-test.js
translations/ui-plugin-create-inventory-records/en.json

Add async barcode validation to make sure barcodes stay unique.
https://issues.folio.org/browse/UIPCIR-24
This PR also includes some console cleanup related to placeholders. It was pretty noisy (about 60 errors in the console).

UIPCIR-24: Add async barcode validation

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIPCIR-25
Increment stripes to v7, react to v17

UIPCIR-25: Increment stripes to v7, react to v17

---

CHANGELOG.md
package.json

Support okapi interfaces `circulation` `12.0`
* Title level requests changes affect ui-requests (UIREQ) without breaking change for this module.
* The implementation of title level requests requires data migration to allow for a single queue of requests, whether item or title level (https://issues.folio.org/browse/UXPROD-3330).
https://issues.folio.org/browse/UIPCIR-30

UIPCIR-30: Also support `circulation` `12.0`

---

CHANGELOG.md
package.json

Support okapi interfaces `circulation` `13.0`
* Title level requests changes affect ui-requests (UIREQ) without breaking change for this module.
* Was changed API associated with request queue.
https://issues.folio.org/browse/UIPCIR-31

UIPCIR-31: Also support circulation 13.0

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml
CHANGELOG.md
src/util.js

https://issues.folio.org/browse/UIPCIR-40
Async barcode validation was executing on every keydown event triggering a fetch to `/inventory/items` which was causing performance issues with a big volume of data (Thank you @zburke for catching this).
This PR wraps the barcode validation in a `debounce` to solve it.

Debounce barcode validation. Fixes UIPCIR-40

---

package.json

https://issues.folio.org/browse/UIPCIR-50

UIPCIR-50: Bump stripes to 8.0.0 for Orchid/2023-R1

---

CHANGELOG.md

https://issues.folio.org/browse/UIPCIR-51

Release v3.3.0

---

CHANGELOG.md
package.json

Also support circulation 14.0
Field fulfilmentPreference was renamed to fulfillmentPreference. This changes do not affect current module.
https://issues.folio.org/browse/UIPCIR-53

UIPCIR-53: Also support circulation 14.0

---

CHANGELOG.md
README.md
src/CreateRecordsPlugin.js
src/CreateRecordsWrapper.js

Added new prop `renderInPaneset` to configure if plugin should render a paneset wrapper
https://github.com/folio-org/ui-plugin-create-inventory-records/assets/19309423/7f62f1f4-08f9-44b3-a475-1c66425bcc67
[UIPCIR-79](https://issues.folio.org/browse/UIPCIR-79)
https://github.com/folio-org/ui-inventory/pull/2347

UIPCIR-79 Added new prop `renderInPaneset` to configure if plugin should render a paneset wrapper

---

CHANGELOG.md
src/util.test.js

Cover util.js with unit tests using Jest + RTL.

UIPCIR-63: Jest/RTL: Cover util.js with unit tests

---

CHANGELOG.md
package.json

* Update dependency `inventory` to `v14.0`
[UIPCIR-85](https://folio-org.atlassian.net/browse/UIPCIR-85)

UIPCIR-85: Support `inventory v14.0`

---

CHANGELOG.md
package.json
src/components/CirculationNoteFields/CirculationNoteFields.test.js

https://folio-org.atlassian.net/browse/UIPCIR-77

UIPCIR-77: Jest/RTL: Cover CirculationNoteFields component with unit tests

---

CHANGELOG.md
src/CreateRecordsPlugin.js

[UIPCIR-81](https://folio-org.atlassian.net/browse/UIPCIR-81)

UIPCIR-81: React v19: refactor away from default props for functional components
