folio-org/ui-plugin-create-inventory-records

- src/util.js
The instance was not created successfully because couple additional props were missing. This PR is addressing that.
> UIPCIR-1: Fix instance parsing

- src/CreateRecordsPlugin.js
- test/bigtest/helpers/PluginHarness.js
Add `open` and `buttonVisible` to the list of plugin props in order to allow for controlling its visibility from the outside.
This should help with the situation described in https://issues.folio.org/browse/UIIN-907
````js
<Pluggable
buttonVisible={false}
open={showNewFastAddModal}
type="create-inventory-records"
id="clickable-create-inventory-records"
onClose={this.toggleNewFastAddModal}
/>
````
> Add ability to control plugin visibility from the outside

- package.json
The `displayName` attribute isn't technically required since translation
of `permissionName` values is handled by the regular translation
mechanism, but some scripts still search by `displayName` so it's
helpful when that value is present.
Refs [UIPCIR-6](https://issues.folio.org/browse/UIPCIR-6)
> UIPCIR-6 include displayName

- CHANGELOG.md
- package.json
Update permission for because of the renaming of instance-bulk endpoint in the scope of the [UIIN-1368](https://issues.folio.org/browse/UIIN-1368).
> UIIN-1368: Update permission for because of renaming of instance-bulk endpoint

- CHANGELOG.md
- README.md
- src/CreateRecordsPlugin.js
- src/CreateRecordsWrapper.js
We're gonna want this for [UICR-91](https://issues.folio.org/browse/UICR-91), which adds Fast Add functionality to the Courses app. The goal is to be able to do the following:
- Hit a `Add Fast Add item` button in Courses.
- This plugin's create-record modal comes up. 
- User fills out the required data, hits `Save and Close`.
- Courses _gets the data (the item's `id`, specifically) of the newly-created record_ and uses that to add a new course reserve item.
The italicised bit in the last item is key and what this PR adds since we otherwise would have to do something like search for the newly-created item which seems subelegant. 
Example usage in parent app:
```
<Pluggable
buttonVisible={false}
id="clickable-create-fast-add-inventory-records"
onClose={({ itemRecord }) => { …
```
> UICR-91: Pass created record's data to onClose

- CHANGELOG.md
- README.md
- src/CreateRecordsPlugin.js
- test/bigtest/interactors/createRecordsPlugin.js
- test/bigtest/tests/render-trigger-test.js
This was borne out of [this discussion on Slack in #stripes](https://folio-project.slack.com/archives/C210UCHQ9/p1608132025330900). 
Basically, an app using this plugin doesn't want to render the trigger/button if the user doesn't have the correct permissions. But to accomplish that, they need to use `IfPermission` along with a permission such as `ui-plugin-create-inventory-records.create`. This means that the app has now implemented a dependency on a specific _implementation_ of a plugin, rather than just a dependency on a _type_ of plugin.
Alternatively, they could construct the entire list of atomic permissions themselves, but that's awful for a variety of reasons including maintenance and code sanity.
By moving the `IfPermission` into the plugin, the plugin ensures it only renders …
> Added IfPermission check and renderTrigger prop

- CHANGELOG.md
- package.json
The only breaking change in `circulation` `10.0` was the removal of the
`override-check-out-by-barcode` which is not used here, hence continuing
to support `9.0`.
Refs [UIPCIR-20(https://issues.folio.org/browse/UIPCIR-20)
> UIPCIR-20 also support circulation 10.0

- CHANGELOG.md
- package.json
There is a breaking change in mod-circulation (https://github.com/folio-org/mod-circulation/pull/854), circulation interface version will be updated to 11.0.  Other modules should update their dependencies to support this change.
**Do not merge. We have several associated pull request and we need merge them at the same time.**
**API changes**
circulation/override-renewal-by-barcode - will be removed
circulation/renew-by-barcode - request and response will be changed
Current changes will be effect ui-users module
https://issues.folio.org/browse/UIPCIR-21
> UIPCIR-21: Update circulation interface dependency to support v11

- CHANGELOG.md
- package.json
Bigtests fails after this [pull request](https://github.com/folio-org/stripes-webpack/pull/43)
Add required mocha version as dependency
https://issues.folio.org/browse/UIPCIR-32
> UIPCIR-32: Update mocha version

- CHANGELOG.md
- package.json
mod-inventory-storage has new major interface versions:
instance-storage 9.0
holdings-storage 6.0
item-storage 10.0
ui-plugin-create-inventory-records is not affected because the incompatible change is in the DELETE all APIs only.
Only the okapiInterfaces need to be bumped in package.json.
> UIPCIR-42: instance-storage 9.0, holdings-storage 6.0, item-storage 10.0

- CHANGELOG.md
- package.json
Add version `12.0` to the list of supported `inventory` interface versions.
`DELETE /inventory/instances` and `DELETE /inventory/items` have been deleting all records.
MODINV-731 changed them to delete records by CQL, this requires a major interface version bump.
ui-plugin-create-inventory-records doesn't use these two `DELETE` APIs therefore no code change is needed.
> UIPCIR-44: Support inventory 12.0 in okapiInterfaces

- CHANGELOG.md
- src/CreateRecordsWrapper.js
- src/providers/DataProvider.js
- src/util.js
- test/bigtest/network/config.js
UIPCIR-47: Set correct `sourceId` on holdings records. Fixes UIPCIR-47.
https://issues.folio.org/browse/UIPCIR-47
> UIPCIR-47: Set correct `sourceId` on holdings records. Fixes UIPCIR-47.

- CHANGELOG.md
- src/CreateRecordsForm.js
- translations/ui-plugin-create-inventory-records/en.json
[UIPCIR-52](https://issues.folio.org/browse/UIPCIR-52)
The original work done in: https://github.com/folio-org/ui-plugin-create-inventory-records/pull/136
> UIPCIR-52:Fast Add an Instance record - UX consistency: Use Save & close button label stripes-component translation key 

- CHANGELOG.md
- src/CreateRecordsPlugin.test.js
[UIPCIR-65](https://folio-org.atlassian.net/browse/UIPCIR-65)
> UIPCIR-65: Cover `CreateRecordsPlugin` component with unit tests

- CHANGELOG.md
- src/hooks/tests/useIsLoading.test.js
Cover useIsLoading hook with unit tests using Jest + RTL. Make sure that test coverage is not lower than 80%.
https://folio-org.atlassian.net/browse/UIPCIR-69
> UIPCIR-69: Jest/RTL: Cover useIsLoading hook with unit tests

- CHANGELOG.md
- src/components/HoldingAccordion/HoldingAccordion.test.js
[UIPCIR-74](https://folio-org.atlassian.net/browse/UIPCIR-74)
> UIPCIR-74: Jest/RTL: Cover `HoldingAccordion` component with unit tests

- CHANGELOG.md
- src/providers/DataProvider.test.js
[UIPCIR-67](https://folio-org.atlassian.net/browse/UIPCIR-67)
> UIPCIR-67: Cover `DataProvider` component with unit tests

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
* Remove pipeline failures by bumping `actions/upload-artifact` to `v4`.
[UIPCIR-87](https://folio-org.atlassian.net/browse/UIPCIR-87)
> UIPCIR-87: Update `actions/upload-artifact@v2` to `actions/upload-artifact@v4`

- CHANGELOG.md
- package.json
* Update dependency `instance-storage` to `v11.0`
[UIPCIR-86](https://folio-org.atlassian.net/browse/UIPCIR-86)
> UIPCIR-86: Support `instance-storage v11.0`

- CHANGELOG.md
- package.json
[UIPCIR-83](https://folio-org.atlassian.net/browse/UIPCIR-83)
Upgrade the API version in the package.json:
-holdings-storage 8.0
> UIPCIR-83: Support `holdings-storage` `8.0`

- CHANGELOG.md
- package.json
- src/components/ContributorFields/ContributorFields.test.js
[UIPCIR-76](https://folio-org.atlassian.net/browse/UIPCIR-76)
> UIPCIR-76: Cover ContributorFields component with unit tests
